server:
  port: 8089
spring:
  application:
    name: MultiTenant
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: mynewpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
          
  main:
    allow-circular-references: true